<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKyi2Lxs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKyi2Lxs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKyi2Lxs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKyi2Lxs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKyi2Lxs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Kyi2Lxs',
    'container.build_id' => '18b569a8',
    'container.build_time' => 1590013725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKyi2Lxs');
