<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD5n9Dnx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD5n9Dnx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD5n9Dnx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD5n9Dnx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerD5n9Dnx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'D5n9Dnx',
    'container.build_id' => '15f61a23',
    'container.build_time' => 1590004226,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD5n9Dnx');
